name: CICD

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '18'

      - name: Build Project
        run: mvn clean install -DskipTests

      - name: Login to Docker Hub
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}

      - name: Clear Docker build cache
        run: docker builder prune -a -f

      - name: Build Docker image
        run: docker build -t ooussama020899/eureka --no-cache .

      - name: Publish image to Docker Hub
        run: docker push oussama020899/eureka:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: SSH to OVH Server
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.OVH_SERVER_HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.OVH_SERVER_PASSWORD }}
          port: ${{ secrets.OVH_SERVER_PORT }}
          script: |
           sudo docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
           sudo docker pull oussama020899/eureka:latest
           sudo docker stop oussama020899/eureka || true
           sudo docker rm eureka || true
           sudo docker run -d --name eureka -p 9091:9091 oussama020899/eureka:latest
